
# coding: utf-8

# # Machine Learning Engineer Nanodegree
# ## Deep Learning
# ## Project: Build a Digit Recognition Program
# 
# In this notebook, a template is provided for you to implement your functionality in stages which is required to successfully complete this project. If additional code is required that cannot be included in the notebook, be sure that the Python code is successfully imported and included in your submission, if necessary. Sections that begin with **'Implementation'** in the header indicate where you should begin your implementation for your project. Note that some sections of implementation are optional, and will be marked with **'Optional'** in the header.
# 
# In addition to implementing code, there will be questions that you must answer which relate to the project and your implementation. Each section where you will answer a question is preceded by a **'Question'** header. Carefully read each question and provide thorough answers in the following text boxes that begin with **'Answer:'**. Your project submission will be evaluated based on your answers to each of the questions and the implementation you provide.
# 
# >**Note:** Code and Markdown cells can be executed using the **Shift + Enter** keyboard shortcut. In addition, Markdown cells can be edited by typically double-clicking the cell to enter edit mode.

# ----
# ## Step 1: Design and Test a Model Architecture
# Design and implement a deep learning model that learns to recognize sequences of digits. Train the model using synthetic data generated by concatenating character images from [notMNIST](http://yaroslavvb.blogspot.com/2011/09/notmnist-dataset.html) or [MNIST](http://yann.lecun.com/exdb/mnist/). To produce a synthetic sequence of digits for testing, you can for example limit yourself to sequences up to five digits, and use five classifiers on top of your deep network. You would have to incorporate an additional ‘blank’ character to account for shorter number sequences.
# 
# There are various aspects to consider when thinking about this problem:
# - Your model can be derived from a deep neural net or a convolutional network.
# - You could experiment sharing or not the weights between the softmax classifiers.
# - You can also use a recurrent network in your deep neural net to replace the classification layers and directly emit the sequence of digits one-at-a-time.
# 
# Here is an example of a [published baseline model on this problem](http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/42241.pdf). ([video](https://www.youtube.com/watch?v=vGPI_JvLoN0))

# ### Implementation
# Use the code cell (or multiple code cells, if necessary) to implement the first step of your project. Once you have completed your implementation and are satisfied with the results, be sure to thoroughly answer the questions that follow.

# In[1]:

### Your code implementation goes here.
### Feel free to use as many code cells as needed.
import scipy.io
train_data = scipy.io.loadmat('train_32x32.mat')
test_data = scipy.io.loadmat('test_32x32.mat')


# In[17]:

print (test_data['X'][0][0][0][0])
X_train = train_data['X']
Y_train = train_data['y']

X_test = test_data['X']
Y_test = test_data['y']

print (X_train[:,:,:,1][31])


# In[21]:

# from PIL import Image
# import numpy as np
from matplotlib import pyplot as plt


# In[49]:

# w = 32
# h = 32
# data = np.zeros((h, w, 3), dtype=np.uint8)


for i in range (0, 10) :
    plt.imshow(X_train[:,:,:,i], interpolation='nearest')
    plt.title(Y_train[i])
    plt.show()


# In[27]:

X_train[:,:,:,0].shape


# In[46]:

def conv_to_greyscale(image):
    grey = np.zeros((image.shape[0], image.shape[1])) # init 2D numpy array
    # get row number
    def average(pixel):
        return np.average(pixel)
        #return 0.299*pixel[0] + 0.587*pixel[1] + 0.114*pixel[2]

    for rownum in range(len(image)):
       for colnum in range(len(image[rownum])):
          grey[rownum][colnum] = average(image[rownum][colnum])
    
    return grey
        


# In[50]:

image = X_train[:,:,:,123]

plt.imshow(conv_to_greyscale(image), interpolation='nearest')
plt.show()
print(conv_to_greyscale(image).shape)
plt.imshow(image, interpolation='nearest')
plt.show()
print(image.shape)
grey.shape


# In[70]:

def greyscale_dataset(X_data) :
    X_new = np.zeros((X_data.shape[0], X_data.shape[1], X_data.shape[3]))
    print ('shape of initial dataset : ' + str(X_data.shape))
    
    for i in range(0, X_data.shape[3]) :
        img = X_data[:,:,:,i]
        X_new[:,:,i] = conv_to_greyscale(img)
        
        one_fourth_percent = X_data.shape[3]/4
        half_percent = 2 * one_fourth_percent
        three_fourth_percent = 3 * one_fourth_percent
        hundred_percent = X_data.shape[3]
        
        if i == one_fourth_percent:
            print ('25% done')
        elif (i == X_data.shape[3]/10):
            print ('10% done')
        elif (i == (X_data.shape[3]*4)/10):
            print ('40% done')
        elif (i == (X_data.shape[3]*6)/10):
            print ('60% done')
        elif (i == (X_data.shape[3]*8)/10):
            print ('80% done')
        elif (i == (X_data.shape[3]*9)/10):
            print ('90% done')
        elif (i == half_percent):
            print ('50% done')
        elif i == three_fourth_percent:
            print ('75% done')
        elif i == hundred_percent:
            print ('100% done')
    print('shape of final dataset : ' + str(X_new.shape))
    print ('dataset - done')
    return X_new


# In[71]:

X_test_grey = greyscale_dataset(X_test)
X_train_grey = greyscale_dataset(X_train)

# X_train_new = np.zeros((X_train.shape[0], X_train.shape[1], X_train.shape[3]))
# h = len(X_train[:,:,:,0])
# # w = len()
# print (X_train.shape)
# print(X_train.shape[3])

# for i in range(0, X_train.shape[3]) :
#     img = X_train[:,:,:,i]
#     X_train_new[:,:,i] = conv_to_greyscale(img)

# new_mat = [[0 for x in range(h)] for y in range(h)] 
# for i in range (0,h):
#     mat = X_train[:,:,:,0][i]
#     for j in range(0, len(mat)):
#         mat[j] = (mat[j][0] + mat[j][1] + mat[j][2])/3
#     new_mat[i] = mat


# In[72]:

print (X_test_grey.shape)
print (X_train_grey.shape)


# In[74]:




# In[75]:

train_grey = {}
train_grey['X'] = X_train_grey
train_grey['y'] = Y_train

test_grey = {}
test_grey['X'] = X_test_grey
test_grey['y'] = Y_test


# In[76]:

scipy.io.savemat('train_32x32_grey.mat', train_grey)


# In[77]:

scipy.io.savemat('test_32x32_grey.mat', test_grey)


# ### Question 1
# _What approach did you take in coming up with a solution to this problem?_

# **Answer:** 

# ### Question 2
# _What does your final architecture look like? (Type of model, layers, sizes, connectivity, etc.)_

# **Answer:**

# ### Question 3
# _How did you train your model? How did you generate your synthetic dataset?_ Include examples of images from the synthetic data you constructed.

# **Answer:**

# ----
# ## Step 2: Train a Model on a Realistic Dataset
# Once you have settled on a good architecture, you can train your model on real data. In particular, the [Street View House Numbers (SVHN)](http://ufldl.stanford.edu/housenumbers/) dataset is a good large-scale dataset collected from house numbers in Google Street View. Training on this more challenging dataset, where the digits are not neatly lined-up and have various skews, fonts and colors, likely means you have to do some hyperparameter exploration to perform well.

# ### Implementation
# Use the code cell (or multiple code cells, if necessary) to implement the first step of your project. Once you have completed your implementation and are satisfied with the results, be sure to thoroughly answer the questions that follow.

# In[ ]:



### Your code implementation goes here.
### Feel free to use as many code cells as needed.



# ### Question 4
# _Describe how you set up the training and testing data for your model. How does the model perform on a realistic dataset?_

# **Answer:**

# ### Question 5
# _What changes did you have to make, if any, to achieve "good" results? Were there any options you explored that made the results worse?_

# **Answer:**

# ### Question 6
# _What were your initial and final results with testing on a realistic dataset? Do you believe your model is doing a good enough job at classifying numbers correctly?_

# **Answer:**

# ----
# ## Step 3: Test a Model on Newly-Captured Images
# 
# Take several pictures of numbers that you find around you (at least five), and run them through your classifier on your computer to produce example results. Alternatively (optionally), you can try using OpenCV / SimpleCV / Pygame to capture live images from a webcam and run those through your classifier.

# ### Implementation
# Use the code cell (or multiple code cells, if necessary) to implement the first step of your project. Once you have completed your implementation and are satisfied with the results, be sure to thoroughly answer the questions that follow.

# In[ ]:



### Your code implementation goes here.
### Feel free to use as many code cells as needed.



# ### Question 7
# _Choose five candidate images of numbers you took from around you and provide them in the report. Are there any particular qualities of the image(s) that might make classification difficult?_

# **Answer:**

# ### Question 8
# _Is your model able to perform equally well on captured pictures or a live camera stream when compared to testing on the realistic dataset?_

# **Answer:**

# ### Optional: Question 9
# _If necessary, provide documentation for how an interface was built for your model to load and classify newly-acquired images._

# **Answer:** Leave blank if you did not complete this part.

# ----
# ### Step 4: Explore an Improvement for a Model
# 
# There are many things you can do once you have the basic classifier in place. One example would be to also localize where the numbers are on the image. The SVHN dataset provides bounding boxes that you can tune to train a localizer. Train a regression loss to the coordinates of the bounding box, and then test it. 

# ### Implementation
# Use the code cell (or multiple code cells, if necessary) to implement the first step of your project. Once you have completed your implementation and are satisfied with the results, be sure to thoroughly answer the questions that follow.

# In[ ]:



### Your code implementation goes here.
### Feel free to use as many code cells as needed.



# ### Question 10
# _How well does your model localize numbers on the testing set from the realistic dataset? Do your classification results change at all with localization included?_

# **Answer:**

# ### Question 11
# _Test the localization function on the images you captured in **Step 3**. Does the model accurately calculate a bounding box for the numbers in the images you found? If you did not use a graphical interface, you may need to investigate the bounding boxes by hand._ Provide an example of the localization created on a captured image.

# **Answer:**

# ----
# ## Optional Step 5: Build an Application or Program for a Model
# Take your project one step further. If you're interested, look to build an Android application or even a more robust Python program that can interface with input images and display the classified numbers and even the bounding boxes. You can for example try to build an augmented reality app by overlaying your answer on the image like the [Word Lens](https://en.wikipedia.org/wiki/Word_Lens) app does.
# 
# Loading a TensorFlow model into a camera app on Android is demonstrated in the [TensorFlow Android demo app](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android), which you can simply modify.
# 
# If you decide to explore this optional route, be sure to document your interface and implementation, along with significant results you find. You can see the additional rubric items that you could be evaluated on by [following this link](https://review.udacity.com/#!/rubrics/413/view).

# ### Optional Implementation
# Use the code cell (or multiple code cells, if necessary) to implement the first step of your project. Once you have completed your implementation and are satisfied with the results, be sure to thoroughly answer the questions that follow.

# In[ ]:



### Your optional code implementation goes here.
### Feel free to use as many code cells as needed.



# ### Documentation
# Provide additional documentation sufficient for detailing the implementation of the Android application or Python program for visualizing the classification of numbers in images. It should be clear how the program or application works. Demonstrations should be provided. 

# _Write your documentation here._

# > **Note**: Once you have completed all of the code implementations and successfully answered each question above, you may finalize your work by exporting the iPython Notebook as an HTML document. You can do this by using the menu above and navigating to  
# **File -> Download as -> HTML (.html)**. Include the finished document along with this notebook as your submission.
